# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_fb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Chandigarh', max_length=70, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='India', max_length=70, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='house_no',
            field=models.CharField(default=' ', max_length=100, verbose_name='house-no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='landmark'),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(default=160014, max_length=7, verbose_name='pincode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=160014, max_length=70, verbose_name='state'),
            preserve_default=False,
        ),
    ]
