# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180410_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100, verbose_name='house-no')),
                ('landmark', models.CharField(blank=True, max_length=50, null=True, verbose_name='landmark')),
                ('city', models.CharField(max_length=70, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='MasterAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=7, verbose_name='pincode')),
                ('district', models.CharField(max_length=70, verbose_name='district')),
                ('state', models.CharField(max_length=70, verbose_name='state')),
                ('country', models.CharField(max_length=70, verbose_name='country')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='MasterAddress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.MasterAddress'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
