# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180411_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='MasterAddress',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=' ', max_length=70, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(default=' ', max_length=7, verbose_name='pincode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=' ', max_length=70, verbose_name='state'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MasterAddress',
        ),
    ]
