# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180411_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialProfile',
        ),
    ]
