# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180413_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
