# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_order_order_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='bk_id',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='order_detail',
        ),
    ]
