# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180426_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('bk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bk_id', to='catalog.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='catalog.Order')),
            ],
        ),
    ]
