# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_orderdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'OrderDetail', 'verbose_name_plural': 'OrderDetails'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='Total_amt',
        ),
    ]
