# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20180426_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
