# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_order_total_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='slug',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('dispatched', 'dispatched'), ('delivered', 'Delivered')], max_length=30),
        ),
    ]
