# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20180501_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='slug',
        ),
    ]
